import { build } from 'esbuild';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const logo = await readFile(new URL('../src/openrouter_image_mcp/ui/northwestern-logo.png', import.meta.url));

async function bundleViewer(name) {
  const source = new URL(`./src/${name}.js`, import.meta.url);
  let template = await readFile(new URL(`./src/${name}.html`, import.meta.url), 'utf8');
  if (name === 'settings') {
    for (const asset of ['product-original', 'product-edited', 'product-mask']) {
      const bytes = await readFile(new URL(`./src/assets/${asset}.webp`, import.meta.url));
      template = template.replaceAll(`PRODUCT_ASSET:${asset}`, `data:image/webp;base64,${bytes.toString('base64')}`);
    }
  }
  const result = await build({
    entryPoints: [fileURLToPath(source)],
    bundle: true, write: false, format: 'iife', platform: 'browser',
    loader: { '.svg': 'dataurl' }, target: 'es2022', minify: true, legalComments: 'inline', metafile: true,
  });

  // Preserve upstream license notices in each self-contained distributed file.
  const packageNames = new Set(Object.values(result.metafile.outputs).flatMap(output =>
    Object.entries(output.inputs).filter(([, input]) => input.bytesInOutput > 0)
      .map(([path]) => path.replaceAll('\\', '/').match(/(?:^|\/)node_modules\/((?:@[^/]+\/)?[^/]+)/)?.[1])
      .filter(Boolean)));
  const licenses = await Promise.all([...packageNames].sort().map(async packageName => {
    for (const filename of ['LICENSE', 'LICENSE.md', 'LICENSE.txt']) {
      try {
        return `${packageName}\n${await readFile(new URL(`./node_modules/${packageName}/${filename}`, import.meta.url), 'utf8')}`;
      } catch (error) {
        if (error.code !== 'ENOENT') throw error;
      }
    }
    throw new Error(`Missing license notice for bundled dependency ${packageName}`);
  }));
  const logoNotice = name === 'preview' ? '' : await readFile(new URL('./src/assets/PROVIDER-LOGOS-LICENSE.txt', import.meta.url), 'utf8');
  const licenseText = [...licenses, logoNotice].join('\n\n').replaceAll('--', '- -').replace(/[ \t]+$/gm, '');
  const notice = `<!-- Generated by ui/build.mjs. Rebuild with npm ci && npm run build.\n${licenseText}\n-->\n`;
  const script = result.outputFiles[0].text.replaceAll('</script', '<\\/script');
  const html = template.replace(/^<!doctype html>/i, match => `${match}\n${notice}`)
    .replace('<!-- APP_LOGO -->', () => `<img class="app-logo" alt="" aria-hidden="true" src="data:image/png;base64,${logo.toString('base64')}">`)
    .replace('<!-- BUNDLED_SCRIPT -->', () => `<script>${script}</script>`);
  const output = new URL(`../src/openrouter_image_mcp/ui/${name}.html`, import.meta.url);
  await mkdir(new URL('.', output), { recursive: true });
  await writeFile(output, html, 'utf8');
  console.log(`Bundled ${name}.html (${Buffer.byteLength(html, 'utf8')} bytes)`);
}

for (const name of ['preview', 'advisor', 'settings']) await bundleViewer(name);
