import { build } from 'esbuild';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const source = new URL('./src/preview.js', import.meta.url);
const template = await readFile(new URL('./src/preview.html', import.meta.url), 'utf8');
const logo = await readFile(new URL('../src/openrouter_image_mcp/ui/northwestern-logo.png', import.meta.url));
const result = await build({
  entryPoints: [fileURLToPath(source)],
  bundle: true, write: false, format: 'iife', platform: 'browser',
  target: 'es2022', minify: true, legalComments: 'inline', metafile: true,
});

// Preserve upstream license notices in the self-contained distributed file.
const packageNames = new Set(Object.values(result.metafile.outputs).flatMap(output =>
  Object.entries(output.inputs).filter(([, input]) => input.bytesInOutput > 0)
    .map(([path]) => path.replaceAll('\\', '/').match(/(?:^|\/)node_modules\/((?:@[^/]+\/)?[^/]+)/)?.[1])
    .filter(Boolean)));
const licenses = await Promise.all([...packageNames].sort().map(async name => {
  for (const filename of ['LICENSE', 'LICENSE.md', 'LICENSE.txt']) {
    try {
      return `${name}\n${await readFile(new URL(`./node_modules/${name}/${filename}`, import.meta.url), 'utf8')}`;
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
  }
  throw new Error(`Missing license notice for bundled dependency ${name}`);
}));
const licenseText = licenses.join('\n\n').replaceAll('--', '- -').replace(/[ \t]+$/gm, '');
const notice = `<!-- Generated by ui/build.mjs. Rebuild with npm ci && npm run build.\n${licenseText}\n-->\n`;
const script = result.outputFiles[0].text.replaceAll('</script', '<\\/script');
const html = template.replace(/^<!doctype html>/i, match => `${match}\n${notice}`)
  .replace('<!-- APP_LOGO -->', () => `<img class="app-logo" alt="" aria-hidden="true" src="data:image/png;base64,${logo.toString('base64')}">`)
  .replace('<!-- BUNDLED_SCRIPT -->', () => `<script>${script}</script>`);
const output = new URL('../src/openrouter_image_mcp/ui/preview.html', import.meta.url);
await mkdir(new URL('.', output), { recursive: true });
await writeFile(output, html, 'utf8');
console.log(`Bundled preview.html (${Buffer.byteLength(html, 'utf8')} bytes)`);
